package com.upiscamshield.utils

import android.content.Context
import com.itextpdf.kernel.colors.ColorConstants
import com.itextpdf.kernel.pdf.PdfDocument
import com.itextpdf.kernel.pdf.PdfWriter
import com.itextpdf.layout.Document
import com.itextpdf.layout.element.Paragraph
import com.itextpdf.layout.element.Table
import com.itextpdf.layout.properties.TextAlignment
import com.upiscamshield.data.model.QRScan
import com.upiscamshield.data.model.RiskLevel
import java.io.File
import java.text.SimpleDateFormat
import java.util.*

object PDFExporter {
    
    fun exportScanToPDF(context: Context, scan: QRScan): File {
        val pdfDir = File(context.getExternalFilesDir(null), "PDFs")
        if (!pdfDir.exists()) {
            pdfDir.mkdirs()
        }
        
        val timestamp = SimpleDateFormat("yyyyMMdd_HHmmss", Locale.getDefault()).format(Date())
        val pdfFile = File(pdfDir, "UPI_Scan_Report_$timestamp.pdf")
        
        val writer = PdfWriter(pdfFile)
        val pdfDocument = PdfDocument(writer)
        val document = Document(pdfDocument)
        
        // Title
        document.add(
            Paragraph("UPI Scam Shield - Scan Report")
                .setFontSize(20f)
                .setBold()
                .setTextAlignment(TextAlignment.CENTER)
        )
        
        document.add(Paragraph("\n"))
        
        // Scan Date
        val dateFormat = SimpleDateFormat("MMM dd, yyyy HH:mm:ss", Locale.getDefault())
        document.add(
            Paragraph("Scan Date: ${dateFormat.format(Date(scan.scannedAt))}")
                .setFontSize(12f)
        )
        
        document.add(Paragraph("\n"))
        
        // UPI Details Table
        document.add(Paragraph("UPI Details").setBold().setFontSize(14f))
        val detailsTable = Table(2)
        detailsTable.addCell("UPI ID")
        detailsTable.addCell(scan.upiId)
        
        scan.merchantName?.let {
            detailsTable.addCell("Merchant Name")
            detailsTable.addCell(it)
        }
        
        scan.amount?.let {
            detailsTable.addCell("Amount")
            detailsTable.addCell("₹$it")
        }
        
        scan.transactionNote?.let {
            detailsTable.addCell("Transaction Note")
            detailsTable.addCell(it)
        }
        
        document.add(detailsTable)
        document.add(Paragraph("\n"))
        
        // Risk Assessment
        document.add(Paragraph("Risk Assessment").setBold().setFontSize(14f))
        
        val riskColor = when (scan.riskLevel) {
            RiskLevel.SAFE -> ColorConstants.GREEN
            RiskLevel.LOW -> ColorConstants.LIGHT_GRAY
            RiskLevel.MEDIUM -> ColorConstants.ORANGE
            RiskLevel.HIGH -> ColorConstants.RED
            RiskLevel.CRITICAL -> ColorConstants.RED
        }
        
        document.add(
            Paragraph("Risk Level: ${scan.riskLevel.name}")
                .setFontColor(riskColor)
                .setBold()
        )
        
        document.add(
            Paragraph("Risk Score: ${String.format("%.1f", scan.riskScore * 100)}%")
        )
        
        document.add(Paragraph("\n"))
        
        // Risk Factors
        if (scan.riskFactors.isNotEmpty()) {
            document.add(Paragraph("Risk Factors:").setBold())
            scan.riskFactors.forEach { factor ->
                document.add(Paragraph("• $factor").setFontSize(11f))
            }
        }
        
        document.add(Paragraph("\n"))
        
        // Footer
        document.add(
            Paragraph("Generated by UPI Scam Shield")
                .setFontSize(10f)
                .setTextAlignment(TextAlignment.CENTER)
                .setFontColor(ColorConstants.GRAY)
        )
        
        document.close()
        
        return pdfFile
    }
}
